### ISSUE TITLE
Quitting using q does not remove the boxes created by aardvark

### ISSUE THREAD

**Issue by sabberworm** [dvogel/AardvarkDuex#2]
Thanks for packaging aardvark into an extension. This way it works even on https sites.

However, I did have a problem when quitting aardvark. The help and info boxes (of class `aardvarkdbox`) stay visible:

<img width="234" alt="Screenshot 2020-09-23 at 16 14 34" src="https://user-images.githubusercontent.com/47652/94024618-efaa9d80-fdb7-11ea-90ce-aec444512499.png">

Additionally, the Firefox browser console says the following:

<img width="724" alt="Screenshot 2020-09-23 at 16 14 43" src="https://user-images.githubusercontent.com/47652/94024641-f6d1ab80-fdb7-11ea-8e79-8f1bb5fc9842.png">

**Comment by dvogel** [comment]
Hi @sabberworm, thanks for letting me know about the issue you experienced. Can you share with me the version of firefox you're using?

**Comment by sabberworm** [comment]
I’m running 80.0.1. The issue happens both on Linux and macOS.

**Comment by dvogel** [comment]
Hi @sabberworm. I've tracked down the source of the issue. With the latest changes the key box should disappear very shortly after it first appears. That was the original behavior. It broke when firefox made some security improvements. What used to be a warning about a legacy approach is now simply not allowed. The new version should be published to the firefox add-on store soon. I'm just waiting on their approval.
