### ISSUE TITLE
karmatics.com/aardvark/

### ISSUE THREAD

**Issue by sjehuda** [dvogel/AardvarkDuex#4]
Ask Rob to link to this repository and to the installation page from https://karmatics.com/aardvark/

Extension banner
https://www.karmatics.com/aardvark/img/bg_mast.gif

**Comment by dvogel** [comment]
Rob is aware of this extension. According to the website he is no longer the owner and the linked vark.com is a dead link for me. I think we'll have to blaze our own trail :)
